name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Debug
      run: |
        echo "github.ref -> ${{ github.ref }}
        echo "github.run_number -> ${{ github.run_number }}"
    
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: registry.wong.dog:5000
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag rushia-fridge-bot:$(date +%s)

    - name: set NOW
      run: |
        echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          registry.wong.dog:5000/rushia-fridge-bot:${{ env.NOW }}
          registry.wong.dog:5000/rushia-fridge-bot:latest

